version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  excute_cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/sample_stack.yml --stack-name sampleStack

workflows:
  raisetech-live15-demo-20231216-workflow:
    jobs:
      - excute_cloudformation
