version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  excute_cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/sample_stack.yml --stack-name sampleStack
  execute_ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '99:aa:df:0f:d2:ee:fe:c8:fb:4a:36:41:c8:88:77:01'
      - ansible-playbook/install:
          version: 2.9.23
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory --private-key ~/.ssh/id_rsa'

workflows:
  raisetech-live15-demo-20231216-workflow:
    jobs:
      - excute_cloudformation
